#!/bin/sh
### BEGIN INIT INFO
# Provides:             recause
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    recause - Log management server
# Description:          recause - Log management server
### END INIT INFO

DAEMON=/usr/local/bin/recause
RUNDIR=/var/run/recause
PIDFILE=$RUNDIR/recause.pid
CONFIGFILE=/etc/recause/config.cfg
ARGS="-c=$CONFIGFILE -pid=$PIDFILE"
NAME="recause"

test -x $DAEMON || exit 0

case "$1" in
    start)
        if start-stop-daemon -b --start --quiet --pidfile $PIDFILE --chuid recause:recause --exec $DAEMON -- $ARGS
        then
            echo "$NAME started."
        else
            echo "$NAME starting failed."
        fi
        ;;
    stop)
        if start-stop-daemon --stop --signal INT --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
        then
            echo "$NAME stopped."
        else
            echo "$NAME stop failed"
        fi
        sleep 1
        ;;
    restart)
        ${0} stop
        ${0} start
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
